

export const CREATE_CANDIDATE_REQUEST = 'CREATE_CANDIDATE_REQUEST'
export const CREATE_CANDIDATE_SUCCESS = 'CREATE_CANDIDATE_SUCCESS'
export const CREATE_CANDIDATE_FAIL = 'CREATE_CANDIDATE_FAIL'
export const CREATE_CANDIDATE_RESET = 'CREATE_CANDIDATE_RESET'




export const UPDATE_CANDIDATE_REQUEST = 'UPDATE_CANDIDATE_REQUEST'
export const UPDATE_CANDIDATE_SUCCESS = 'UPDATE_CANDIDATE_SUCCESS'
export const UPDATE_CANDIDATE_FAIL = 'UPDATE_CANDIDATE_FAIL'
export const UPDATE_CANDIDATE_RESET = 'UPDATE_CANDIDATE_RESET'

export const DELETE_CANDIDATE_REQUEST = 'DELETE_CANDIDATE_REQUEST'
export const DELETE_CANDIDATE_SUCCESS = 'DELETE_CANDIDATE_SUCCESS'
export const DELETE_CANDIDATE_FAIL = 'DELETE_CANDIDATE_FAIL'
export const DELETE_CANDIDATE_RESET = 'DELETE_CANDIDATE_RESET'




export const GET_ALL_CANDIDATES_REQUEST = 'GET_ALL_CANDIDATES_REQUEST'
export const GET_ALL_CANDIDATES_SUCCESS = 'GET_ALL_CANDIDATES_SUCCESS'
export const GET_ALL_CANDIDATES_FAIL = 'GET_ALL_CANDIDATES_FAIL'


export const GET_SINGLE_CANDIDATE_REQUEST = 'GET_SINGLE_CANDIDATE_REQUEST'
export const GET_SINGLE_CANDIDATE_SUCCESS = 'GET_SINGLE_CANDIDATE_SUCCESS'
export const GET_SINGLE_CANDIDATE_FAIL = 'GET_SINGLE_CANDIDATE_FAIL'
