

export const CREATE_SUBE_REQUEST = 'CREATE_SUBE_REQUEST'
export const CREATE_SUBE_SUCCESS = 'CREATE_SUBE_SUCCESS'
export const CREATE_SUBE_FAIL = 'CREATE_SUBE_FAIL'
export const CREATE_SUBE_RESET = 'CREATE_SUBE_RESET'




export const UPDATE_SUBE_REQUEST = 'UPDATE_SUBE_REQUEST'
export const UPDATE_SUBE_SUCCESS = 'UPDATE_SUBE_SUCCESS'
export const UPDATE_SUBE_FAIL = 'UPDATE_SUBE_FAIL'
export const UPDATE_SUBE_RESET = 'UPDATE_SUBE_RESET'

export const DELETE_SUBE_REQUEST = 'DELETE_SUBE_REQUEST'
export const DELETE_SUBE_SUCCESS = 'DELETE_SUBE_SUCCESS'
export const DELETE_SUBE_FAIL = 'DELETE_SUBE_FAIL'
export const DELETE_SUBE_RESET = 'DELETE_SUBE_RESET'




export const GET_ALL_SUBES_REQUEST = 'GET_ALL_SUBES_REQUEST'
export const GET_ALL_SUBES_SUCCESS = 'GET_ALL_SUBES_SUCCESS'
export const GET_ALL_SUBES_FAIL = 'GET_ALL_SUBES_FAIL'


export const GET_SINGLE_SUBE_REQUEST = 'GET_SINGLE_SUBE_REQUEST'
export const GET_SINGLE_SUBE_SUCCESS = 'GET_SINGLE_SUBE_SUCCESS'
export const GET_SINGLE_SUBE_FAIL = 'GET_SINGLE_SUBE_FAIL'
